/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javanunes;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardo
 */
public class FormView extends javax.swing.JFrame {
    
    private  VermutController vermutController = new VermutController();
    private DadosModel db = new DadosModel();

    /**
     * Creates new form FORM
     */
    public FormView() {
        initComponents();
        setResizable(false);
        setCbPlacasRede(db.getPlacasDeRede());
        setCbVulnerabilidades(db.getTiposAtaques());
        setCbHosts(db.getIpsPreDefinidos());
        setCbCanalWifi(db.getChanelWifi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTipoAtaque = new javax.swing.JComboBox();
        cbIPsPreDefinidos = new javax.swing.JComboBox();
        txtPorta = new javax.swing.JTextField();
        btGerarCavaloDeTroia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbPlacaDeRede = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbChanelWifi = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtMac = new javax.swing.JTextField();
        btPreparar = new javax.swing.JButton();
        btAtacar = new javax.swing.JButton();
        btWifiteMonitor = new javax.swing.JButton();
        btAiroDump = new javax.swing.JButton();
        rdEhAquela = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaStatus = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vermut ");

        txtPorta.setText("8080");

        btGerarCavaloDeTroia.setText("GERAR VENON");
        btGerarCavaloDeTroia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarCavaloDeTroiaActionPerformed(evt);
            }
        });

        jLabel1.setText("PLACA:");

        jLabel2.setText("CANAL");

        cbChanelWifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChanelWifiActionPerformed(evt);
            }
        });

        jLabel3.setText("MAC");

        txtMac.setText("00:00:00:00:00:00");

        btPreparar.setText("Preparar");
        btPreparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrepararActionPerformed(evt);
            }
        });

        btAtacar.setText("Atacar");
        btAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtacarActionPerformed(evt);
            }
        });

        btWifiteMonitor.setText("WIFI MONITOR");
        btWifiteMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWifiteMonitorActionPerformed(evt);
            }
        });

        btAiroDump.setText("AIROUDUM MONITOR");
        btAiroDump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAiroDumpActionPerformed(evt);
            }
        });

        rdEhAquela.setText("E AQUELA?");
        rdEhAquela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEhAquelaActionPerformed(evt);
            }
        });

        txaStatus.setColumns(20);
        txaStatus.setRows(5);
        jScrollPane1.setViewportView(txaStatus);

        jLabel4.setText("O que foi usado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbPlacaDeRede, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbChanelWifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cbTipoAtaque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(cbIPsPreDefinidos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btGerarCavaloDeTroia))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btAiroDump, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btWifiteMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdEhAquela)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtMac, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btPreparar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btAtacar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))))
                    .addComponent(jLabel4))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cbTipoAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbIPsPreDefinidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerarCavaloDeTroia))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPlacaDeRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbChanelWifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPreparar)
                    .addComponent(btAtacar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdEhAquela)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAiroDump)
                    .addComponent(btWifiteMonitor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerarCavaloDeTroiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarCavaloDeTroiaActionPerformed
        // TODO add your handling code here:]
        vermutController.FazerTrojam();  
        atualizaStatus();
        
        
    }//GEN-LAST:event_btGerarCavaloDeTroiaActionPerformed

    private void cbChanelWifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChanelWifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChanelWifiActionPerformed

    private void btPrepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrepararActionPerformed
        // TODO add your handling code here:
        vermutController.PreparaPlacaParaAtaque();
        atualizaStatus();
    }//GEN-LAST:event_btPrepararActionPerformed

    private void btWifiteMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWifiteMonitorActionPerformed
        // TODO add your handling code here:
        vermutController.MonitorWifiWifite();
        atualizaStatus();
        
    }//GEN-LAST:event_btWifiteMonitorActionPerformed

    private void btAiroDumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAiroDumpActionPerformed
        // TODO add your handling code here:
        vermutController.MonitorAiroDump();
        atualizaStatus();
    }//GEN-LAST:event_btAiroDumpActionPerformed

    private void rdEhAquelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEhAquelaActionPerformed
        // TODO add your handling code here:
        this.BotaMacAddressDaquelaInfeliz();
        atualizaStatus();
        
    }//GEN-LAST:event_rdEhAquelaActionPerformed

    private void btAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtacarActionPerformed
        // TODO add your handling code here:]
        vermutController.Atacar();
        atualizaStatus();
    }//GEN-LAST:event_btAtacarActionPerformed

    private void cbPlacaDeRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlacaDeRedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlacaDeRedeActionPerformed

    public void MessageBox(String mensagem){
       JOptionPane.showMessageDialog (null, mensagem); 
    }
    
    public void BotaMacAddressDaquelaInfeliz(){
        txtMac.setText("F4:54:20:0B:6E:C3");
    }
    
    public void setTxaStatus(String mensagem){
        if(mensagem.equals("")){
            this.MessageBox("Estranho Nao chegou nada");
        }
        txaStatus.setText(mensagem);
    }
    
    public String getMac(){
        return txtMac.getText();
    }
    
    public String getTxtPorta(){
        return txtPorta.getText();
    }
    
    public String getCbChanelWifi(){
        return cbChanelWifi.getSelectedItem().toString();
    }
    
    public String getCbHost(){
        return cbIPsPreDefinidos.getSelectedItem().toString();
    }
    
    public String getCbPlacaDeRede(){
        return cbPlacaDeRede.getSelectedItem().toString();
    }
    
    public String getCbTipoAtaque(){
        return cbTipoAtaque.getSelectedItem().toString();
    }
    
    public void setEnableBtPreparar(boolean status){
        btPreparar.setEnabled(status);
    }
    
    public void setCbPlacasRede(String[] placas){     
        for (String plaquinha :  placas){
           cbPlacaDeRede.addItem(plaquinha);
        }
    }
    
    public void setCbVulnerabilidades(String[] vulns){     
        for (String vulnerabilidades :  vulns){
           cbTipoAtaque.addItem(vulnerabilidades);
        }
    }
   
     public void setCbHosts(String[] hosts){     
        for (String host :  hosts){
           cbIPsPreDefinidos.addItem(host);
        }
    }
    
     public void setCbCanalWifi(String[] canais){     
        for (String canal :  canais){
           cbChanelWifi.addItem(canal);
        }
    } 
    
    public void atualizaStatus(){
        txaStatus.setText(db.getStatusFezPorUltimo());
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAiroDump;
    private javax.swing.JButton btAtacar;
    private javax.swing.JButton btGerarCavaloDeTroia;
    private javax.swing.JButton btPreparar;
    private javax.swing.JButton btWifiteMonitor;
    private javax.swing.JComboBox cbChanelWifi;
    private javax.swing.JComboBox cbIPsPreDefinidos;
    private javax.swing.JComboBox cbPlacaDeRede;
    private javax.swing.JComboBox cbTipoAtaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdEhAquela;
    private javax.swing.JTextArea txaStatus;
    private javax.swing.JTextField txtMac;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables
}
